export enum AuditAction {
  LOGIN_SUCCESS = 'LOGIN_SUCCESS', LOGIN_FAILED = 'LOGIN_FAILED', ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  ACCOUNT_UNLOCKED = 'ACCOUNT_UNLOCKED', PASSWORD_CHANGED = 'PASSWORD_CHANGED', PASSWORD_RESET = 'PASSWORD_RESET',
  ACCOUNT_ACTIVATED = 'ACCOUNT_ACTIVATED', USER_CREATED = 'USER_CREATED', USER_UPDATED = 'USER_UPDATED',
  USER_ROLE_CHANGED = 'USER_ROLE_CHANGED', USER_ACTIVATED = 'USER_ACTIVATED', USER_DEACTIVATED = 'USER_DEACTIVATED',
  USER_REQUEST_CREATED = 'USER_REQUEST_CREATED', USER_REQUEST_APPROVED = 'USER_REQUEST_APPROVED', USER_REQUEST_REJECTED = 'USER_REQUEST_REJECTED',
}
