import { Navigate, Route, Routes } from 'react-router-dom'
import { ProtectedRoute } from '../auth/ProtectedRoute'
import { RoleRoute } from '../auth/RoleRoute'
import { AppLayout } from '../layouts/AppLayout'
import { ForgotPasswordPage } from '../pages/ForgotPasswordPage'
import { LoginPage } from '../pages/LoginPage'
import { NotFoundPage } from '../pages/NotFoundPage'
import { ProfilePage } from '../pages/ProfilePage'
import { RegisterPage } from '../pages/RegisterPage'
import { TokenPasswordPage } from '../pages/TokenPasswordPage'
import { AuditLogsPage } from '../pages/admin/AuditLogsPage'
import { UserRequestsPage } from '../pages/admin/UserRequestsPage'
import { UsersPage } from '../pages/admin/UsersPage'
import { ForbiddenPage } from '../pages/ForbiddenPage'
export function AppRoutes() { return <Routes><Route path="/" element={<Navigate to="/profile" replace/>}/><Route path="/login" element={<LoginPage/>}/><Route path="/register" element={<RegisterPage/>}/><Route path="/activate-account" element={<TokenPasswordPage mode="activate"/>}/><Route path="/forgot-password" element={<ForgotPasswordPage/>}/><Route path="/reset-password" element={<TokenPasswordPage mode="reset"/>}/><Route path="/403" element={<ForbiddenPage/>}/><Route element={<ProtectedRoute/>}><Route element={<AppLayout/>}><Route path="/profile" element={<ProfilePage/>}/><Route element={<RoleRoute role="Administrador"/>}><Route path="/admin/users" element={<UsersPage/>}/><Route path="/admin/user-requests" element={<UserRequestsPage/>}/><Route path="/admin/audit-logs" element={<AuditLogsPage/>}/></Route></Route></Route><Route path="*" element={<NotFoundPage/>}/></Routes> }
