import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { describe, expect, it, beforeEach, vi } from 'vitest'
import { LoginPage } from './LoginPage'
const auth = vi.hoisted(() => ({ login: vi.fn(), isAuthenticated: false }))
vi.mock('../model/AuthContext', () => ({ useAuth: () => auth }))
function renderPage(entry = '/login') { return render(<MemoryRouter initialEntries={[entry]}><Routes><Route path="/login" element={<LoginPage/>}/><Route path="/profile" element={<p>Profile</p>}/><Route path="/app" element={<p>Dashboard</p>}/></Routes></MemoryRouter>) }
describe('LoginPage', () => { beforeEach(() => { vi.clearAllMocks(); auth.isAuthenticated = false })
  it('renders the access actions and relies on required fields validation', () => { renderPage(); expect(screen.getByRole('heading', { name: 'Iniciar sesión' })).toBeInTheDocument(); expect(screen.getByLabelText('Correo electrónico')).toBeRequired(); expect(screen.getByLabelText('Contraseña')).toBeRequired(); expect(screen.getByRole('link', { name: 'Solicitar una cuenta' })).toHaveAttribute('href', '/register') })
  it('shows loading, prevents a double submit, and redirects after success', async () => { let resolve!: (u: any) => void; auth.login.mockReturnValue(new Promise(r => { resolve = r })); renderPage('/login'); fireEvent.change(screen.getByLabelText('Correo electrónico'), { target: { value: 'a@b.cr' } }); fireEvent.change(screen.getByLabelText('Contraseña'), { target: { value: 'valid-secret' } }); fireEvent.click(screen.getByRole('button', { name: 'Iniciar sesión' })); const submitButton = screen.getByRole('button', { name: 'Ingresando…' }); expect(submitButton).toBeDisabled(); fireEvent.click(submitButton); expect(auth.login).toHaveBeenCalledTimes(1); resolve({ role: 'Administrador' }); expect(await screen.findByText('Dashboard')).toBeInTheDocument() })
  it('shows credentials errors and redirects to the saved route on success', async () => { auth.login.mockRejectedValueOnce(new Error('bad')).mockResolvedValueOnce({ role: 'Usuario' }); renderPage({ pathname: '/login', state: { from: { pathname: '/profile' } } } as any); fireEvent.change(screen.getByLabelText('Correo electrónico'), { target: { value: 'a@b.cr' } }); fireEvent.change(screen.getByLabelText('Contraseña'), { target: { value: 'valid-secret' } }); fireEvent.click(screen.getByRole('button', { name: 'Iniciar sesión' })); expect(await screen.findByRole('alert')).toHaveTextContent('credenciales'); fireEvent.click(screen.getByRole('button', { name: 'Iniciar sesión' })); await waitFor(() => expect(screen.getByText('Profile')).toBeInTheDocument()) })
})
