import { useEffect, useId, useState, type ReactNode } from 'react'
import { Link, NavLink } from 'react-router-dom'
import { moduleAvailability, site, services } from '../../content/publicSiteContent'
import { useAuth } from '../../auth/AuthContext'

export function Seo({ title, description }: { title: string; description: string }) { useEffect(() => { document.title = `${title} | ADI Curime`; let meta = document.querySelector('meta[name="description"]'); if (!meta) { meta = document.createElement('meta'); meta.setAttribute('name', 'description'); document.head.append(meta) }; meta.setAttribute('content', description) }, [title, description]); return null }
function Brand() { return <Link className="public-brand" to="/" aria-label={`${site.shortName}, inicio`}><span className="brand-mark" aria-hidden="true">C</span><span><strong>{site.shortName}</strong><small>Desarrollo comunitario</small></span></Link> }
export function PublicHeader() { const { isAuthenticated } = useAuth(); const [open, setOpen] = useState(false); const id = useId(); useEffect(() => { const escape = (event: KeyboardEvent) => { if (event.key === 'Escape') setOpen(false) }; window.addEventListener('keydown', escape); return () => window.removeEventListener('keydown', escape) }, []); const close = () => setOpen(false); return <header className="public-header"><div className="public-nav-wrap"><Brand /><button className="public-menu-button" onClick={() => setOpen(!open)} aria-label="Abrir menú de navegación" aria-expanded={open} aria-controls={id}>Menú</button><nav id={id} className={`public-nav ${open ? 'is-open' : ''}`} aria-label="Navegación pública">{site.nav.map(item => <NavLink key={item.to} to={item.to} end={item.to === '/'} onClick={close}>{item.label}</NavLink>)}<Link className="button button-small" to={isAuthenticated ? '/app' : '/login'} onClick={close}>{isAuthenticated ? 'Ir al SGI' : 'Iniciar sesión'}</Link></nav></div></header> }
export function PublicFooter() { return <footer className="public-footer"><div className="footer-grid"><div><strong>{site.shortName}</strong><p>{site.slogan}</p><p>{site.location}<br /><a href={`mailto:${site.email}`}>{site.email}</a><br /><span aria-label="Instagram">Instagram: {site.instagram}</span></p></div><nav aria-label="Enlaces del pie"><strong>Navegación</strong>{site.nav.slice(0, 5).map(item => <Link key={item.to} to={item.to}>{item.label}</Link>)}<Link to="/app">Acceso al SGI</Link></nav></div><p className="footer-copy">© {new Date().getFullYear()} {site.shortName}. Todos los derechos reservados.</p></footer> }
export function SectionContainer({ children, className = '' }: { children: ReactNode; className?: string }) { return <section className={`section container-public ${className}`}>{children}</section> }
export function SectionHeader({ eyebrow, title, text }: { eyebrow?: string; title: string; text?: string }) { return <header className="section-header">{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h2>{title}</h2>{text && <p>{text}</p>}</header> }
export function PublicPageHeader({ title, intro }: { title: string; intro: string }) { return <header className="page-header"><div className="container-public"><p className="eyebrow">ADI Curime</p><h1>{title}</h1><p>{intro}</p></div></header> }
export function Breadcrumbs({ current }: { current: string }) { return <nav className="breadcrumbs container-public" aria-label="Migas de pan"><Link to="/">Inicio</Link><span aria-hidden="true">/</span><span aria-current="page">{current}</span></nav> }
export function StatusBadge({ status }: { status: string }) { return <span className={`status-badge status-${status}`}>{status === 'próximo' ? 'Próximo' : status === 'finalizado' ? 'Finalizado' : status === 'cancelado' ? 'Cancelado' : 'Próximamente'}</span> }
export function EmptyContentState({ title = 'Información en preparación', text = site.pending }: { title?: string; text?: string }) { return <div className="empty-state"><h3>{title}</h3><p>{text}</p></div> }
export function ServiceCard({ service }: { service: (typeof services)[number] }) { const affiliation=service.key==='affiliation'&&moduleAvailability.affiliation.enabled; return <article className="service-card"><StatusBadge status={affiliation?'disponible':'próximamente'} /><h3>{service.title}</h3><p>{service.text}</p>{affiliation?<Link to="/afiliacion">Solicitar afiliación</Link>:<span className="muted">Disponible próximamente</span>}</article> }
export function NewsCard({ item }: { item: { slug: string; category: string; date: string; title: string; excerpt: string } }) { return <article className="content-card"><p className="eyebrow">{item.category} · {item.date}</p><h3><Link to={`/noticias/${item.slug}`}>{item.title}</Link></h3><p>{item.excerpt}</p><Link to={`/noticias/${item.slug}`}>Leer noticia<span className="sr-only">: {item.title}</span></Link></article> }
export function EventCard({ item }: { item: { title: string; date: string; time: string; place: string; summary: string; status: string } }) { return <article className="content-card"><StatusBadge status={item.status} /><h3>{item.title}</h3><dl><dt>Fecha</dt><dd>{item.date}</dd><dt>Hora</dt><dd>{item.time}</dd><dt>Lugar</dt><dd>{item.place}</dd></dl><p>{item.summary}</p></article> }
export function CTASection() { const { isAuthenticated } = useAuth(); return <SectionContainer className="cta-section"><div><h2>Construyamos comunidad</h2><p>Conozca el espacio digital de la Asociación y manténgase cerca de la información oficial.</p></div><div className="actions"><Link className="button button-light" to="/contacto">Contáctenos</Link><Link className="button button-outline-light" to={isAuthenticated ? '/app' : '/register'}>{isAuthenticated ? 'Ir al SGI' : 'Solicitar cuenta'}</Link></div></SectionContainer> }
