import { useEffect, type ReactNode } from 'react'
import { Link } from 'react-router-dom'
import { site, services } from '../../content/publicSiteContent'
import { useAuth } from '@/features/auth'

export function Seo({ title, description }: { title: string; description: string }) { useEffect(() => { document.title = `${title} | ADI Curime`; let meta = document.querySelector('meta[name="description"]'); if (!meta) { meta = document.createElement('meta'); meta.setAttribute('name', 'description'); document.head.append(meta) }; meta.setAttribute('content', description) }, [title, description]); return null }
export function SectionContainer({ children, className = '', spacing = 'normal' }: { children: ReactNode; className?: string; spacing?: 'compact' | 'normal' | 'spacious' }) { const spacingClass = spacing === 'compact' ? 'py-10' : spacing === 'spacious' ? 'py-10 md:py-20' : 'py-10 md:py-16'; return <section className={`${spacingClass} container-public ${className}`}>{children}</section> }
export function SectionHeader({ eyebrow, title, text }: { eyebrow?: string; title: string; text?: string }) { return <header className="section-header">{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h2>{title}</h2>{text && <p>{text}</p>}</header> }
export function PublicPageHeader({ title, intro }: { title: string; intro: string }) { return <header className="bg-surface-muted py-10 md:py-16"><div className="container-public"><p className="eyebrow">ADI Curime</p><h1 className="mt-1 text-heading-1 text-primary">{title}</h1><p className="mt-3 max-w-3xl text-body-large text-muted-foreground">{intro}</p></div></header> }
export function Breadcrumbs({ current }: { current: string }) { return <nav className="container-public flex gap-2 py-4 text-body-small text-muted-foreground" aria-label="Migas de pan"><Link className="rounded-sm text-primary underline-offset-4 hover:underline focus-visible:outline-3 focus-visible:outline-offset-2 focus-visible:outline-ring" to="/">Inicio</Link><span aria-hidden="true">/</span><span aria-current="page">{current}</span></nav> }
export function StatusBadge({ status }: { status: string }) { return <span className={`status-badge status-${status}`}>{status === 'próximo' ? 'Próximo' : status === 'finalizado' ? 'Finalizado' : status === 'cancelado' ? 'Cancelado' : 'Próximamente'}</span> }
export function EmptyContentState({ title = 'Información en preparación', text = site.pending }: { title?: string; text?: string }) { return <div className="empty-state"><h3>{title}</h3><p>{text}</p></div> }
export function ServiceCard({ service }: { service: (typeof services)[number] }) { return <article className="service-card"><StatusBadge status="próximamente" /><h3>{service.title}</h3><p>{service.text}</p><span className="muted">Disponible próximamente</span></article> }
export function NewsCard({ item }: { item: { slug: string; category: string; date: string; title: string; excerpt: string } }) { return <article className="content-card"><p className="eyebrow">{item.category} · {item.date}</p><h3><Link to={`/noticias/${item.slug}`}>{item.title}</Link></h3><p>{item.excerpt}</p><Link to={`/noticias/${item.slug}`}>Leer noticia<span className="sr-only">: {item.title}</span></Link></article> }
export function CTASection() { const { isAuthenticated } = useAuth(); return <SectionContainer className="cta-section"><div><h2>Construyamos comunidad</h2><p>Conozca el espacio digital de la Asociación y manténgase cerca de la información oficial.</p></div><div className="actions"><Link className="button button-light" to="/contacto">Contáctenos</Link><Link className="button button-outline-light" to={isAuthenticated ? '/app' : '/register'}>{isAuthenticated ? 'Mi panel' : 'Solicitar una cuenta'}</Link></div></SectionContainer> }
