import { useEffect, type ReactNode } from 'react'
import { Link } from 'react-router-dom'
import { site, services } from '../../content/publicSiteContent'
import { useAuth } from '@/features/auth'
import { homePathForRole } from '@/shared/security/roles'

export function Seo({ title, description }: { title: string; description: string }) { useEffect(() => { document.title = `${title} | ADI Curime`; let meta = document.querySelector('meta[name="description"]'); if (!meta) { meta = document.createElement('meta'); meta.setAttribute('name', 'description'); document.head.append(meta) }; meta.setAttribute('content', description) }, [title, description]); return null }
export function SectionContainer({ children, className = '' }: { children: ReactNode; className?: string }) { return <section className={`section container-public ${className}`}>{children}</section> }
export function SectionHeader({ eyebrow, title, text }: { eyebrow?: string; title: string; text?: string }) { return <header className="section-header">{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h2>{title}</h2>{text && <p>{text}</p>}</header> }
export function PublicPageHeader({ title, intro }: { title: string; intro: string }) { return <header className="page-header"><div className="container-public"><p className="eyebrow">ADI Curime</p><h1>{title}</h1><p>{intro}</p></div></header> }
export function Breadcrumbs({ current }: { current: string }) { return <nav className="breadcrumbs container-public" aria-label="Migas de pan"><Link to="/">Inicio</Link><span aria-hidden="true">/</span><span aria-current="page">{current}</span></nav> }
export function StatusBadge({ status }: { status: string }) { return <span className={`status-badge status-${status}`}>{status === 'próximo' ? 'Próximo' : status === 'finalizado' ? 'Finalizado' : status === 'cancelado' ? 'Cancelado' : 'Próximamente'}</span> }
export function EmptyContentState({ title = 'Información en preparación', text = site.pending }: { title?: string; text?: string }) { return <div className="empty-state"><h3>{title}</h3><p>{text}</p></div> }
export function ServiceCard({ service }: { service: (typeof services)[number] }) { return <article className="service-card"><StatusBadge status="próximamente" /><h3>{service.title}</h3><p>{service.text}</p><span className="muted">Disponible próximamente</span></article> }
export function NewsCard({ item }: { item: { slug: string; category: string; date: string; title: string; excerpt: string } }) { return <article className="content-card"><p className="eyebrow">{item.category} · {item.date}</p><h3><Link to={`/noticias/${item.slug}`}>{item.title}</Link></h3><p>{item.excerpt}</p><Link to={`/noticias/${item.slug}`}>Leer noticia<span className="sr-only">: {item.title}</span></Link></article> }
export function EventCard({ item }: { item: { title: string; date: string; time: string; place: string; summary: string; status: string } }) { return <article className="content-card"><StatusBadge status={item.status} /><h3>{item.title}</h3><dl><dt>Fecha</dt><dd>{item.date}</dd><dt>Hora</dt><dd>{item.time}</dd><dt>Lugar</dt><dd>{item.place}</dd></dl><p>{item.summary}</p></article> }
export function CTASection() { const { isAuthenticated, user } = useAuth(); return <SectionContainer className="cta-section"><div><h2>Construyamos comunidad</h2><p>Conozca el espacio digital de la Asociación y manténgase cerca de la información oficial.</p></div><div className="actions"><Link className="button button-light" to="/contacto">Contáctenos</Link><Link className="button button-outline-light" to={isAuthenticated ? homePathForRole(user?.role) : '/register'}>{isAuthenticated ? 'Mi cuenta' : 'Solicitar una cuenta'}</Link></div></SectionContainer> }
