import { act, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { describe, expect, it, beforeEach, vi } from 'vitest'
import { AuthProvider, useAuth } from './AuthContext'
import { authService } from '../api/auth.api'
import { sessionStorageService } from '@/shared/session/sessionStorage'

vi.mock('../api/auth.api', () => ({ authService: { me: vi.fn(), login: vi.fn(), logout: vi.fn() } }))
const user = { id: 1, fullName: 'Ana', email: 'ana@curime.cr', role: 'Usuario', status: 'ACTIVE' } as any
function Probe() { const auth = useAuth(); return <><span>{auth.isLoading ? 'loading' : 'ready'}</span><span>{auth.user?.fullName ?? 'anonymous'}</span><span>{auth.token ?? 'no-token'}</span><button onClick={() => void auth.login({ email: 'ana@curime.cr', password: 'not-inspected' }).catch(() => undefined)}>login</button><button onClick={() => void auth.logout()}>logout</button></> }
function renderAuth() { const queryClient = new QueryClient({ defaultOptions: { queries: { retry: false } } }); return { queryClient, ...render(<QueryClientProvider client={queryClient}><AuthProvider><Probe /></AuthProvider></QueryClientProvider>) } }
describe('AuthContext', () => {
  beforeEach(() => { localStorage.clear(); vi.clearAllMocks(); vi.mocked(authService.logout).mockResolvedValue({ message: 'Logged out' }) })
  it('starts loading and restores current user from /users/me', async () => { sessionStorageService.set({ token: 'token', user: { ...user, fullName: 'Old' } }); vi.mocked(authService.me).mockResolvedValue(user); renderAuth(); expect(screen.getByText('loading')).toBeInTheDocument(); await waitFor(() => expect(screen.getByText('Ana')).toBeInTheDocument()); expect(sessionStorageService.get()?.user.fullName).toBe('Ana') })
  it('clears failed restoration locally without backend logout', async () => { sessionStorageService.set({ token: 'token', user }); vi.mocked(authService.me).mockRejectedValue(new Error('401')); renderAuth(); await waitFor(() => expect(screen.getByText('anonymous')).toBeInTheDocument()); expect(sessionStorageService.get()).toBeNull(); expect(authService.logout).not.toHaveBeenCalled() })
  it('clears session, cache, and React state on unauthorized without backend logout', async () => { sessionStorageService.set({ token: 'token', user }); vi.mocked(authService.me).mockResolvedValue(user); const { queryClient } = renderAuth(); await screen.findByText('Ana'); queryClient.setQueryData(['users'], user); act(() => window.dispatchEvent(new Event('auth:unauthorized'))); expect(sessionStorageService.get()).toBeNull(); expect(queryClient.getQueryData(['users'])).toBeUndefined(); expect(screen.getByText('anonymous')).toBeInTheDocument(); expect(screen.getByText('no-token')).toBeInTheDocument(); expect(authService.logout).not.toHaveBeenCalled() })
  it('stores a successful login and applies refreshed access tokens', async () => { vi.mocked(authService.login).mockResolvedValue({ accessToken: 'new-token', user }); renderAuth(); fireEvent.click(screen.getByText('login')); await waitFor(() => expect(sessionStorageService.get()).toEqual({ token: 'new-token', user })); act(() => window.dispatchEvent(new CustomEvent('auth:token-refreshed', { detail: 'refreshed-token' }))); expect(screen.getByText('refreshed-token')).toBeInTheDocument() })
  it('calls backend logout then clears session and query cache', async () => { sessionStorageService.set({ token: 'token', user }); const { queryClient } = renderAuth(); queryClient.setQueryData(['users'], user); fireEvent.click(screen.getByText('logout')); await waitFor(() => expect(authService.logout).toHaveBeenCalledOnce()); expect(sessionStorageService.get()).toBeNull(); expect(queryClient.getQueryData(['users'])).toBeUndefined(); expect(screen.getByText('anonymous')).toBeInTheDocument() })
  it('clears session and cache even if backend logout fails', async () => { sessionStorageService.set({ token: 'token', user }); vi.mocked(authService.logout).mockRejectedValue(new Error('offline')); const { queryClient } = renderAuth(); queryClient.setQueryData(['users'], user); fireEvent.click(screen.getByText('logout')); await waitFor(() => expect(sessionStorageService.get()).toBeNull()); expect(queryClient.getQueryData(['users'])).toBeUndefined(); expect(screen.getByText('anonymous')).toBeInTheDocument() })
  it('does not create a session after an incorrect login', async () => { vi.mocked(authService.login).mockRejectedValue(new Error('bad credentials')); renderAuth(); screen.getByText('login').click(); await waitFor(() => expect(authService.login).toHaveBeenCalledOnce()); expect(sessionStorageService.get()).toBeNull() })
})
