import { useState, type FormEvent } from 'react'
import { getErrorMessage } from '@/shared/lib/errors'
import { Button } from '@/shared/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/shared/ui/card'
import { EmptyState } from '@/shared/ui/EmptyState'
import { ErrorState } from '@/shared/ui/ErrorState'
import { Input } from '@/shared/ui/input'
import { LoadingState } from '@/shared/ui/LoadingState'
import { PageHeader } from '@/shared/ui/PageHeader'
import { Select } from '@/shared/ui/select'
import { useBoardMutations, useBoardTerms, usePersonCandidates } from '../hooks/institutionalBoard.queries'
import { BOARD_POSITIONS, BOARD_POSITION_LABELS, type BoardAppointment, type BoardPosition } from '../model/institutionalBoard.types'

const emptyAppointment = { personId: 0, position: 'PRESIDENT' as BoardPosition, seatNumber: '', startsOn: '', endsOn: '' }
const dateOnly = (value: string | null) => value ? value.slice(0, 10) : 'Según período'
const personName = (a: BoardAppointment) => [a.person.firstName, a.person.firstSurname, a.person.secondSurname].filter(Boolean).join(' ') || a.person.legacyFullName || `Persona ${a.personId}`

export function InstitutionalBoardPage() {
  const terms = useBoardTerms(); const mutations = useBoardMutations()
  const [selectedId, setSelectedId] = useState<number | null>(null)
  const selected = terms.data?.find(term => term.id === selectedId) ?? terms.data?.[0]
  const [term, setTerm] = useState({ startsOn: '', endsOn: '' })
  const [appointment, setAppointment] = useState(emptyAppointment)
  const [editing, setEditing] = useState<BoardAppointment | null>(null)
  const [query, setQuery] = useState(''); const candidates = usePersonCandidates(query)
  const [message, setMessage] = useState('')
  const submitTerm = async (e: FormEvent) => { e.preventDefault(); setMessage(''); try { await mutations.createTerm.mutateAsync(term); setTerm({ startsOn: '', endsOn: '' }) } catch (error) { setMessage(getErrorMessage(error)) } }
  const submitAppointment = async (e: FormEvent) => { e.preventDefault(); if (!selected || (!editing && !appointment.personId)) return; setMessage(''); const commonInput = { position: appointment.position, seatNumber: appointment.seatNumber ? Number(appointment.seatNumber) : null, startsOn: appointment.startsOn || null, endsOn: appointment.endsOn || null }; try { if (editing) await mutations.updateAppointment.mutateAsync({ id: editing.id, input: commonInput }); else await mutations.createAppointment.mutateAsync({ termId: selected.id, input: { personId: appointment.personId, ...commonInput } }); setAppointment(emptyAppointment); setEditing(null); setQuery('') } catch (error) { setMessage(getErrorMessage(error)) } }
  const edit = (item: BoardAppointment) => { setEditing(item); setQuery(''); setAppointment({ personId: item.personId, position: item.position, seatNumber: item.seatNumber?.toString() ?? '', startsOn: dateOnly(item.startsOn) === 'Según período' ? '' : dateOnly(item.startsOn), endsOn: dateOnly(item.endsOn) === 'Según período' ? '' : dateOnly(item.endsOn) }) }
  return <section className="space-y-6">
    <PageHeader context="Gestión administrativa" title="Junta Directiva" description="Períodos y nombramientos institucionales históricos." />
    <div className="rounded-control border border-border bg-surface-subtle p-4 text-sm">Registre aquí los nombramientos institucionales confirmados por la Asociación. Esta información no sustituye actas, firmas ni documentos oficiales.</div>
    {message ? <ErrorState title="No fue posible guardar" message={message} /> : null}
    <Card><CardHeader><CardTitle>Nuevo período</CardTitle><CardDescription>Las fechas no se calculan automáticamente.</CardDescription></CardHeader><CardContent><form className="grid gap-4 sm:grid-cols-3" onSubmit={submitTerm}><label className="grid gap-2 text-sm font-semibold">Desde<Input type="date" required value={term.startsOn} onChange={e => setTerm({ ...term, startsOn: e.target.value })} /></label><label className="grid gap-2 text-sm font-semibold">Hasta<Input type="date" required value={term.endsOn} onChange={e => setTerm({ ...term, endsOn: e.target.value })} /></label><div className="self-end"><Button type="submit" disabled={mutations.createTerm.isPending}>{mutations.createTerm.isPending ? 'Guardando…' : 'Crear período'}</Button></div></form></CardContent></Card>
    {terms.isPending ? <LoadingState label="Cargando períodos..." /> : null}{terms.isError ? <ErrorState title="No fue posible cargar los períodos" message={getErrorMessage(terms.error)} /> : null}
    {terms.data?.length === 0 ? <EmptyState title="No hay períodos registrados" description="Cree el primer período para registrar nombramientos." /> : null}
    {terms.data?.length ? <div className="grid gap-6 lg:grid-cols-[18rem_1fr]"><Card><CardHeader><CardTitle>Períodos</CardTitle></CardHeader><CardContent><div className="grid gap-2">{terms.data.map(item => <Button key={item.id} type="button" variant={selected?.id === item.id ? 'default' : 'outline'} onClick={() => setSelectedId(item.id)}>{dateOnly(item.startsOn)} — {dateOnly(item.endsOn)}</Button>)}</div></CardContent></Card><div className="space-y-6"><Card><CardHeader><CardTitle>Nombramientos</CardTitle><CardDescription>Período {dateOnly(selected!.startsOn)} al {dateOnly(selected!.endsOn)}. El historial se conserva; no hay eliminación.</CardDescription></CardHeader><CardContent>{selected!.appointments.length === 0 ? <EmptyState title="Sin nombramientos" description="Agregue un nombramiento confirmado." /> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-2">Cargo</th><th className="p-2">Persona</th><th className="p-2">Plaza</th><th className="p-2">Vigencia</th><th className="p-2"><span className="sr-only">Acciones</span></th></tr></thead><tbody>{selected!.appointments.map(item => <tr key={item.id} className="border-t"><td className="p-2">{BOARD_POSITION_LABELS[item.position]}</td><td className="p-2">{personName(item)}</td><td className="p-2">{item.seatNumber ?? '—'}</td><td className="p-2">{dateOnly(item.startsOn)} — {dateOnly(item.endsOn)}</td><td className="p-2"><Button type="button" variant="outline" onClick={() => edit(item)}>Editar</Button></td></tr>)}</tbody></table></div>}</CardContent></Card>
    <Card><CardHeader><CardTitle>{editing ? 'Editar nombramiento' : 'Agregar nombramiento'}</CardTitle></CardHeader><CardContent><form className="grid gap-4 md:grid-cols-2" onSubmit={submitAppointment}>{editing ? <div className="grid gap-2 md:col-span-2"><span className="text-sm font-semibold">Persona</span><p className="rounded-control border border-border bg-surface-subtle p-3" aria-label="Persona del nombramiento">{personName(editing)}</p><p className="text-sm text-foreground-muted">Para registrar una sustitución, cierre la vigencia de este nombramiento y cree uno nuevo para la nueva persona.</p></div> : <><label className="grid gap-2 text-sm font-semibold md:col-span-2">Buscar persona<Input value={query} onChange={e => { setQuery(e.target.value); setAppointment({ ...appointment, personId: 0 }) }} placeholder="Nombre o identificación" aria-describedby="person-help" /><span id="person-help" className="font-normal text-foreground-muted">Escriba al menos dos caracteres y seleccione una persona existente.</span></label>{candidates.data?.length ? <div className="grid gap-2 md:col-span-2" role="listbox" aria-label="Personas encontradas">{candidates.data.map(person => <Button key={person.id} type="button" variant={appointment.personId === person.id ? 'default' : 'outline'} onClick={() => { setAppointment({ ...appointment, personId: person.id }); setQuery(person.displayName) }}>{person.displayName} {person.identificationHint ? `(${person.identificationType ?? 'ID'} ${person.identificationHint})` : ''}</Button>)}</div> : null}</>}<label className="grid gap-2 text-sm font-semibold">Cargo<Select value={appointment.position} onChange={e => setAppointment({ ...appointment, position: e.target.value as BoardPosition })}>{BOARD_POSITIONS.map(p => <option key={p} value={p}>{BOARD_POSITION_LABELS[p]}</option>)}</Select></label><label className="grid gap-2 text-sm font-semibold">Plaza (opcional)<Input type="number" min="1" value={appointment.seatNumber} onChange={e => setAppointment({ ...appointment, seatNumber: e.target.value })} /></label><label className="grid gap-2 text-sm font-semibold">Desde (opcional)<Input type="date" value={appointment.startsOn} onChange={e => setAppointment({ ...appointment, startsOn: e.target.value })} /></label><label className="grid gap-2 text-sm font-semibold">Hasta (opcional)<Input type="date" value={appointment.endsOn} onChange={e => setAppointment({ ...appointment, endsOn: e.target.value })} /></label><div className="flex gap-2 md:col-span-2"><Button type="submit" disabled={(!editing && !appointment.personId) || mutations.createAppointment.isPending || mutations.updateAppointment.isPending}>{editing ? 'Guardar cambios' : 'Agregar nombramiento'}</Button>{editing ? <Button type="button" variant="outline" onClick={() => { setEditing(null); setAppointment(emptyAppointment); setQuery('') }}>Cancelar</Button> : null}</div></form></CardContent></Card></div></div> : null}
  </section>
}
