import { fireEvent, render, screen, waitFor } from '@testing-library/react'; import type { ReactNode } from 'react'; import { MemoryRouter, Route, Routes } from 'react-router-dom'; import { beforeEach, describe, expect, it, vi } from 'vitest'; import { ToastProvider } from '../../components/Toast'
import { AffiliateRequestsPage } from './AffiliateRequestsPage'; import { AffiliatesPage } from './AffiliatesPage'; import { AssembliesPage } from './AssembliesPage'; import { AttendancePage } from './AttendancePage'; import { JustificationsPage } from './JustificationsPage'; import { SanctionsPage } from './SanctionsPage'; import { AdminReportsPage } from './AdminReportsPage'
import { affiliateRequestsService } from '../../services/affiliateRequestsService'; import { affiliatesService } from '../../services/affiliatesService'; import { assembliesService } from '../../services/assembliesService'; import { absenceJustificationsService } from '../../services/absenceJustificationsService'; import { sanctionsService } from '../../services/sanctionsService'; import { adminReportsService } from '../../services/adminReportsService'
vi.mock('../../services/affiliateRequestsService',()=>({affiliateRequestsService:{list:vi.fn(),get:vi.fn(),approve:vi.fn(),reject:vi.fn()}}));vi.mock('../../services/affiliatesService',()=>({affiliatesService:{list:vi.fn(),get:vi.fn(),update:vi.fn(),activate:vi.fn(),deactivate:vi.fn(),allActive:vi.fn()}}));vi.mock('../../services/assembliesService',()=>({assembliesService:{list:vi.fn(),get:vi.fn(),create:vi.fn(),update:vi.fn(),attendance:vi.fn(),saveAttendance:vi.fn()}}));vi.mock('../../services/absenceJustificationsService',()=>({absenceJustificationsService:{list:vi.fn(),approve:vi.fn(),reject:vi.fn()}}));vi.mock('../../services/sanctionsService',()=>({sanctionsService:{list:vi.fn(),byAffiliate:vi.fn(),create:vi.fn(),update:vi.fn()}}));vi.mock('../../services/adminReportsService',()=>({adminReportsService:{affiliates:vi.fn(),attendance:vi.fn(),justifications:vi.fn(),sanctions:vi.fn()}}))
const page=<T,>(data:T[])=>({data,total:data.length,page:1,limit:10});const affiliate={id:1,fullName:'Ana Pérez',identification:'1-111',birthDate:'1990-01-01T00:00:00Z',gender:null,phone:'8888',email:'ana@test.cr',address:'Curime',occupation:null,workplace:null,affiliateType:'Regular',affiliationDate:'2026-01-01T00:00:00Z',status:'ACTIVE' as const,createdAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-01T00:00:00Z'};const assembly={id:2,title:'Asamblea agosto',type:'Ordinaria',date:'2026-08-15T18:00:00Z',place:'Salón',description:'Informe',status:'SCHEDULED' as const,createdAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-01T00:00:00Z'}
function ui(node:ReactNode,path='/'){const pattern=path.includes('/attendance')?'/admin/assemblies/:id/attendance':'*';return render(<MemoryRouter initialEntries={[path]}><ToastProvider><Routes><Route path={pattern} element={node}/></Routes></ToastProvider></MemoryRouter>)}
beforeEach(()=>{vi.clearAllMocks();vi.mocked(affiliatesService.allActive).mockResolvedValue([affiliate]);vi.mocked(assembliesService.list).mockResolvedValue(page([assembly]))})
describe('frontend administrativo',()=>{
 it('lista y aprueba solicitudes de afiliación',async()=>{const request={...affiliate,affiliationReason:'Participar',status:'PENDING' as const,rejectionReason:null,reviewedAt:null,reviewedById:null,reviewedBy:null};vi.mocked(affiliateRequestsService.list).mockResolvedValue(page([request]));vi.mocked(affiliateRequestsService.approve).mockResolvedValue({});ui(<AffiliateRequestsPage/>);expect(await screen.findByText('Ana Pérez')).toBeInTheDocument();fireEvent.click(screen.getByText('Ver detalle'));fireEvent.click(screen.getByText('Aprobar'));fireEvent.click(screen.getByText('Aprobar solicitud'));await waitFor(()=>expect(affiliateRequestsService.approve).toHaveBeenCalledWith(1))})
 it('muestra detalle, edita y cambia estado de afiliado',async()=>{vi.mocked(affiliatesService.list).mockResolvedValue(page([affiliate]));vi.mocked(affiliatesService.get).mockResolvedValue(affiliate);vi.mocked(affiliatesService.deactivate).mockResolvedValue({...affiliate,status:'INACTIVE'});ui(<AffiliatesPage/>);fireEvent.click(await screen.findByText('Ver detalle'));expect(await screen.findByText('Curime')).toBeInTheDocument();fireEvent.click(screen.getByText('Inactivar'));fireEvent.click(screen.getByText('Confirmar'));await waitFor(()=>expect(affiliatesService.deactivate).toHaveBeenCalledWith(1))})
 it('lista, crea y abre edición de asambleas',async()=>{vi.mocked(assembliesService.list).mockResolvedValue(page([assembly]));vi.mocked(assembliesService.create).mockResolvedValue(assembly);ui(<AssembliesPage/>);expect(await screen.findByText('Asamblea agosto')).toBeInTheDocument();fireEvent.click(screen.getByText('Crear asamblea'));expect(screen.getByRole('dialog')).toBeInTheDocument();fireEvent.click(screen.getByText('Cancelar'));fireEvent.click(screen.getByText('Editar'));expect(screen.getByDisplayValue('Asamblea agosto')).toBeInTheDocument()})
 it('cambia estados y guarda asistencia masiva con métricas',async()=>{vi.mocked(assembliesService.get).mockResolvedValue(assembly);vi.mocked(assembliesService.attendance).mockResolvedValue({assemblyId:2,totalActive:1,present:0,absent:0,justified:0,unrecorded:1,attendancePercentage:0,data:[]});vi.mocked(assembliesService.saveAttendance).mockResolvedValue({assemblyId:2,totalActive:1,present:1,absent:0,justified:0,unrecorded:0,attendancePercentage:100,data:[]});ui(<AttendancePage/>,'/admin/assemblies/2/attendance');expect(await screen.findByText('Ana Pérez')).toBeInTheDocument();fireEvent.change(screen.getByLabelText('Estado de Ana Pérez'),{target:{value:'PRESENT'}});fireEvent.click(screen.getByText('Guardar asistencia'));await waitFor(()=>expect(assembliesService.saveAttendance).toHaveBeenCalledWith(2,[{affiliateId:1,status:'PRESENT'}]))})
 it('lista y aprueba justificaciones',async()=>{const j={id:3,reason:'Enfermedad',status:'PENDING' as const,rejectionReason:null,reviewedAt:null,reviewedById:null,assemblyId:2,affiliateId:1,assembly:{id:2,title:assembly.title,date:assembly.date},affiliate:{id:1,fullName:affiliate.fullName,identification:affiliate.identification},reviewedBy:null,createdAt:assembly.createdAt,updatedAt:assembly.updatedAt};vi.mocked(absenceJustificationsService.list).mockResolvedValue(page([j]));vi.mocked(absenceJustificationsService.approve).mockResolvedValue(j);ui(<JustificationsPage/>);fireEvent.click(await screen.findByText('Detalle'));fireEvent.click(screen.getByText('Aprobar'));fireEvent.click(screen.getByText('Confirmar'));await waitFor(()=>expect(absenceJustificationsService.approve).toHaveBeenCalledWith(3))})
 it('lista y abre creación/edición de sanciones',async()=>{const s={id:4,reason:'Incumplimiento',description:'Detalle',date:assembly.date,status:'ACTIVE' as const,affiliateId:1,affiliate:{id:1,fullName:affiliate.fullName,identification:affiliate.identification,status:'ACTIVE' as const},createdById:9,createdBy:{id:9,fullName:'Admin',email:'admin@test.cr'},createdAt:assembly.createdAt,updatedAt:assembly.updatedAt};vi.mocked(sanctionsService.list).mockResolvedValue(page([s]));ui(<SanctionsPage/>);expect(await screen.findByText('Incumplimiento')).toBeInTheDocument();fireEvent.click(screen.getByText('Registrar sanción'));expect(screen.getByRole('dialog')).toBeInTheDocument()})
 it('renderiza resúmenes y aplica filtros de reportes',async()=>{vi.mocked(adminReportsService.affiliates).mockResolvedValue({total:2,active:1,inactive:1,pendingRequests:3});vi.mocked(adminReportsService.attendance).mockResolvedValue({assemblies:0,totals:{present:0,absent:0,justified:0},data:[]});vi.mocked(adminReportsService.justifications).mockResolvedValue({total:0,PENDING:0,APPROVED:0,REJECTED:0});vi.mocked(adminReportsService.sanctions).mockResolvedValue({total:0,ACTIVE:0,RESOLVED:0,REVOKED:0});ui(<AdminReportsPage/>);expect(await screen.findByText('Solicitudes pendientes')).toBeInTheDocument();fireEvent.change(screen.getByLabelText('Desde'),{target:{value:'2026-08-01'}});await waitFor(()=>expect(adminReportsService.attendance).toHaveBeenCalledWith(expect.objectContaining({dateFrom:'2026-08-01'})))})
})
