import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { useSearchParams } from 'react-router-dom'
import { Pagination } from '../../components/Pagination'; import { Modal } from '../../components/Modal'; import { StatusBadge, date } from '../../components/admin/AdminUi'; import { useToast } from '../../components/Toast'
import { sanctionsService } from '../../services/sanctionsService'; import { affiliatesService } from '../../services/affiliatesService'; import type { Affiliate } from '../../types/affiliates'; import type { Sanction, SanctionStatus } from '../../types/sanctions'; import { getErrorMessage } from '../../utils/errors'
const limit=10, blank={affiliateId:'',reason:'',description:'',date:'',status:'ACTIVE' as SanctionStatus}
export function SanctionsPage(){
 const {notify}=useToast(), [params]=useSearchParams(); const preset=params.get('affiliateId')||''
 const [items,setItems]=useState<Sanction[]>([]),[affiliates,setAffiliates]=useState<Affiliate[]>([]),[edit,setEdit]=useState<Sanction|null|undefined>(),[detail,setDetail]=useState<Sanction|null>(null),[form,setForm]=useState({...blank,affiliateId:preset})
 const [status,setStatus]=useState<SanctionStatus|''>(''),[affiliateId,setAffiliateId]=useState(preset),[page,setPage]=useState(1),[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await sanctionsService.list({affiliateId:affiliateId?Number(affiliateId):undefined,status:status||undefined,page,limit});setItems(r.data);setTotal(r.total)}catch(e){setError(getErrorMessage(e))}finally{setLoading(false)}},[affiliateId,page,status])
 useEffect(()=>{void load()},[load]);useEffect(()=>{affiliatesService.allActive().then(setAffiliates).catch(()=>undefined)},[])
 function open(x?:Sanction){setEdit(x??null);setForm(x?{affiliateId:String(x.affiliateId),reason:x.reason,description:x.description||'',date:x.date.slice(0,10),status:x.status}:{...blank,affiliateId})}
 async function save(e:FormEvent){e.preventDefault();setBusy(true);try{const payload={reason:form.reason.trim(),description:form.description.trim()||undefined,date:form.date?new Date(`${form.date}T12:00:00`).toISOString():undefined,status:form.status};if(edit)await sanctionsService.update(edit.id,payload);else await sanctionsService.create(Number(form.affiliateId),payload);notify(edit?'Sanción actualizada.':'Sanción registrada.','success');setEdit(undefined);await load()}catch(e){notify(getErrorMessage(e),'error')}finally{setBusy(false)}}
 return <section><div className="page-heading"><h1>Sanciones</h1><button className="primary" onClick={()=>open()}>Registrar sanción</button></div><div className="filters card"><label>Afiliado<select value={affiliateId} onChange={e=>{setPage(1);setAffiliateId(e.target.value)}}><option value="">Todos</option>{affiliates.map(a=><option value={a.id} key={a.id}>{a.fullName}</option>)}</select></label><label>Estado<select value={status} onChange={e=>{setPage(1);setStatus(e.target.value as SanctionStatus|'')}}><option value="">Todos</option><option value="ACTIVE">Activa</option><option value="RESOLVED">Resuelta</option><option value="REVOKED">Revocada</option></select></label></div>{error&&<p className="message error" role="alert">{error}</p>}{loading?<p>Cargando sanciones…</p>:!items.length?<p className="card">No hay sanciones para mostrar.</p>:<><div className="table-wrap"><table><thead><tr><th>Afiliado</th><th>Motivo</th><th>Fecha</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.affiliate.fullName}</td><td>{x.reason}</td><td>{date(x.date)}</td><td><StatusBadge status={x.status}/></td><td><div className="actions"><button onClick={()=>setDetail(x)}>Detalle</button><button onClick={()=>open(x)}>Editar</button></div></td></tr>)}</tbody></table></div><Pagination page={page} total={total} limit={limit} onChange={setPage}/></>}
 {detail&&<Modal title="Detalle de sanción" onClose={()=>setDetail(null)}><dl className="detail-grid"><div><dt>Afiliado</dt><dd>{detail.affiliate.fullName}</dd></div><div><dt>Motivo</dt><dd>{detail.reason}</dd></div><div><dt>Descripción</dt><dd>{detail.description||'—'}</dd></div><div><dt>Fecha</dt><dd>{date(detail.date)}</dd></div><div><dt>Estado</dt><dd><StatusBadge status={detail.status}/></dd></div><div><dt>Registrada por</dt><dd>{detail.createdBy.fullName}</dd></div></dl></Modal>}
 {edit!==undefined&&<Modal title={edit?'Editar sanción':'Registrar sanción'} busy={busy} onClose={()=>setEdit(undefined)}><form className="form-grid" onSubmit={save}><label>Afiliado<select required disabled={Boolean(edit)} value={form.affiliateId} onChange={e=>setForm({...form,affiliateId:e.target.value})}><option value="">Seleccione</option>{affiliates.map(a=><option value={a.id} key={a.id}>{a.fullName} · {a.identification}</option>)}</select></label><label>Motivo<input required maxLength={300} value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label><label>Descripción<textarea maxLength={2000} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Fecha<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Estado<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as SanctionStatus})}><option value="ACTIVE">Activa</option><option value="RESOLVED">Resuelta</option><option value="REVOKED">Revocada</option></select></label><div className="actions"><button type="button" onClick={()=>setEdit(undefined)}>Cancelar</button><button className="primary" disabled={busy||!form.affiliateId}>{busy?'Guardando…':'Confirmar y guardar'}</button></div></form></Modal>}</section>
}
